plugins {
    id 'fabric-loom' version '1.15.5'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = "${project.archives_base_name}-${project.minecraft_version}"
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.fabricmc.net/' }
}

def legacyVersion = project.minecraft_version.split('\\.')
def legacyPatch = legacyVersion.length > 2 ? legacyVersion[2] : '0'
def legacySource = legacyPatch.toInteger() >= 9 ? 'src/legacy-new/java' : 'src/legacy/java'
sourceSets.main.java.srcDirs = [legacySource]

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'minecraft_version', project.minecraft_version

    filesMatching('*.json') {
        expand 'version': project.version,
                'minecraft_version': project.minecraft_version,
                'java_compatibility': '21'
    }
}
